databases:
  - name: postgres
    plan: free
    ipAllowList: []

services:
  - type: web
    name: adhkar-ai
    env: ruby
    plan: free
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec rails runner bin/start_bot.rb
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: OPENAI_SECRET_KEY
        sync: false
      - key: TELEGRAM_API_KEY
        sync: false
  

  - type: redis
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction

  - type: worker
    name: adhkar-ai-worker-1
    env: ruby
    region: oregon
    plan: free
    buildCommand: bundle install
    startCommand: bundle exec rails runner app/integrations/start_bot.rb